function change1() {
    document.getElementById("div2").innerHTML =
      "The Border-Gavaskar Trophy (BGT) is an International Test trophy played between India and Australia. The series is named after distinguished former captains, Australia's Allan Border and India's Sunil Gavaskar. It is played via Test series scheduled using International Cricket Council's Future Tours Programme. The winner of a Test series wins the trophy. If a series is drawn, the country holding the trophy retains it. ";
  }
  function change2() {
    document.getElementById("div2").innerHTML ="The 2021-2023 ICC World Test Championship was the second edition of the ICC World Test Championship of Test cricket.It started on 4 August 2021 and finished with the Final on 7–11 June 2023 at The Oval, London, played between Australia and India.The five-match Pataudi Trophy between England and India, started 4 August 2021, started the second cycle of the World Test Championship."
  }
  function change3() {
    document.getElementById("div2").innerHTML="India have retained the ICC Test Championship Mace and won the purse of $ 1 million for a third year running after finishing at the top of the MRF Tyres ICC Test Team Rankings on the cut-off date of 1 April, while New Zealand have ensured second place"
  }
  function change4() {
    document.getElementById("div2").innerHTML="The India cricket team toured England between July and September 2018 to play five Tests, three One Day International (ODIs) and three Twenty20 International (T20Is) matches.[1][2][3] India also played a three-day match against Essex in July at Chelmsford.India won the T20I series 2–1.[5] In the second T20I, MS Dhoni played in his 500th international cricket match.[6] He became the ninth player overall, and the third Indian, to reach this milestone"
  }
  function changestyle() {
    document.getElementById("div2").style.fontSize = "30px";
    document.getElementById("div2").style.color = "";
  }
  function resetStyle() {
    document.getElementById("div2").style.fontSize = "25px";
    document.getElementById("div2").style.color = "black";
  }